### ISSUE TITLE
Problem finding shortest path on large graphs

### ISSUE THREAD

**Issue by Latek** [mjwach/two-steiner-tree-algorithms-in-java#1]
Did:
Created the EdgeArraysGraph with default options and weighted edges coming from distances of roads in OpenStreetMap roads graph. The graph was created using OSM data from geofabrik.de.
Tried the algorithm on a large graph (> 5000 vertices, > 100 randomly selected terminals).

Happened:
Got exception telling: "no more advancement is possible".

Expected:
To solve the Steiner minimum tree problem without errors.

Note:
I've double-checked the vertices and edges passed to the graph and the path should be found.

**Comment by Latek** [comment]
I think the problem is in the method ShortestPathsTable.getNextVertexOnShortestPath() in lines:

```
int cellIndex = getCellIndex(destinationIndex, sourceIndex);
ensurePenultimateStepValueIsPresent(sourceIndex, cellIndex);	
```

The problem is that for many cases, but not all, the penultimate step is pre-calculated (then it works fine), but this happens not every time. Especially in large graphs, when the penultimate steps are calculated lazily (on demand).

Then the cellIndex calculated in the first of mentioned lines doesn't match the cell index matched in ensurePenultimateStepValueIsPresent() method.

The solution which works for me was to change the above to:
```
int cellIndex = getCellIndex(destinationIndex, sourceIndex);
ensurePenultimateStepValueIsPresent(destinationIndex, cellIndex);	
```

Please verify if my assumptions are correct and fix the problem in the code if it won't affect other parts of the code.

Thank you in advance!

**Comment by mjwach** [comment]
Yes, that appears to be a mistake I made.  I wonder how I never noticed it back when I was using these algorithms!  Your solution is correct, and I've committed it to the repository.  Thanks!

(Without a failing test case, I can't verify that your original problem of the "no more advancement" error is fixed, but it sounds like you have done that yourself.)

**Comment by Latek** [comment]
Thank you!
